import { useEffect, useMemo, useState } from 'react'
import { ArrowDownRight, ArrowLeft, ArrowRight, ArrowUpRight, Menu, X } from 'lucide-react'
import { Link, useLocation, useNavigate, useParams } from 'react-router-dom'
import { categories, projects, type Category, type Project } from './data/projects'

const categoryClass = (category: Category) => category.split(' ')[0].toLowerCase()

function Logo() { return <Link className="logo" to="/">CW<span>•</span>U</Link> }
function Header({ onMenu }: { onMenu: () => void }) {
  const [scrolled, setScrolled] = useState(false)
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 20); window.addEventListener('scroll', onScroll); return () => window.removeEventListener('scroll', onScroll) }, [])
  return <header className={scrolled ? 'site-header scrolled' : 'site-header'}><Logo /><nav className="desktop-nav"><a href="/#projects">Projects <span>↘</span></a><a href="/#categories">Categories <span>↘</span></a><a href="/#about">About <span>↘</span></a></nav><div className="header-actions"><a className="github-link" href="https://github.com/alejandromontillamurillo-cell/mi-proyecto-prueba" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={14} /></a><button className="menu-button" onClick={onMenu} aria-label="Open menu"><Menu size={20} /></button></div></header>
}
function MobileMenu({ close }: { close: () => void }) { return <div className="mobile-menu"><button className="close-menu" onClick={close}><X size={22} /></button><span className="menu-kicker">CWU / NAVIGATION</span><a href="/#projects" onClick={close}>Projects <ArrowDownRight /></a><a href="/#categories" onClick={close}>Categories <ArrowDownRight /></a><a href="/#about" onClick={close}>About <ArrowDownRight /></a><a href="https://github.com/alejandromontillamurillo-cell/mi-proyecto-prueba" target="_blank" rel="noreferrer">GitHub <ArrowUpRight /></a></div> }
function ProjectCard({ project, featured = false }: { project: Project; featured?: boolean }) { return <Link to={project.route} className={`project-card ${featured ? 'featured' : ''} ${categoryClass(project.category)}`} style={{ '--accent': project.accent, '--accent-soft': project.accentSoft } as React.CSSProperties}><div className="card-image"><img src={project.image} alt={`${project.title} project preview`} loading="lazy" /><div className="card-overlay" /></div><div className="card-top"><span>{project.index}</span><span>{project.category.split(' / ')[0]}</span></div><div className="card-bottom"><div><span className="card-eyebrow">{project.eyebrow}</span><h3>{project.title}</h3></div><span className="round-arrow"><ArrowUpRight size={18} /></span></div></Link> }
function Home() {
  const [filter, setFilter] = useState<(typeof categories)[number]>('All projects'); const [showAll, setShowAll] = useState(false)
  const shown = useMemo(() => projects.filter((project) => filter === 'All projects' || project.category === filter), [filter]); const visible = showAll || filter !== 'All projects' ? shown : shown.slice(0, 9)
  return <><section className="hero"><div className="hero-orbit orbit-one" /><div className="hero-orbit orbit-two" /><div className="hero-noise" /><div className="hero-copy"><span className="eyebrow reveal">Independent digital studio / 2024—25</span><h1 className="reveal delay-1">A universe of<br /><em>distinct</em> digital worlds<span className="dot">.</span></h1><p className="hero-intro reveal delay-2">Fifteen experiments in art direction, interaction and code — collected in one living archive.</p><a className="pill-button reveal delay-3" href="#projects">Explore projects <ArrowDownRight size={17} /></a></div><div className="hero-footer"><span>Scroll to explore</span><span className="hero-line" /><span>01 / 15</span></div></section><section className="statement" id="about"><div className="section-label">01 / The idea</div><div className="statement-content"><p>We believe the web should feel less like a template and more like a <span>place you remember.</span></p><div className="statement-meta"><span>Creative Web Universe</span><span>15 projects / 03 worlds</span></div></div></section><section className="showcase" id="projects"><div className="section-heading"><div><span className="section-label">02 / Selected work</span><h2>Explore the<br /><em>collection</em><span className="dot">.</span></h2></div><p>Different briefs. Different atmospheres.<br />One point of view: make it memorable.</p></div><div className="filter-row" id="categories">{categories.map((item) => <button key={item} className={filter === item ? 'active' : ''} onClick={() => { setFilter(item); setShowAll(true) }}>{item}</button>)}</div><div className="project-grid">{visible.map((project, index) => <ProjectCard key={project.id} project={project} featured={index === 0 && filter === 'All projects'} />)}</div>{filter === 'All projects' && !showAll && <button className="load-more" onClick={() => setShowAll(true)}>View all 15 projects <ArrowDownRight size={18} /></button>}</section><section className="manifesto"><div className="manifesto-mark">✳</div><p>Good design makes an entrance.<br /><em>Great design leaves a trace.</em></p><span>03 / A note from the studio</span></section><Footer /></>
}
function Detail() {
  const { id } = useParams(); const project = projects.find((item) => item.id === id) ?? projects[0]; const currentIndex = projects.findIndex((item) => item.id === project.id); const previous = projects[(currentIndex - 1 + projects.length) % projects.length]; const next = projects[(currentIndex + 1) % projects.length]; useEffect(() => window.scrollTo(0, 0), [id])
  return <main className={`detail-page detail-${categoryClass(project.category)}`} style={{ '--accent': project.accent, '--accent-soft': project.accentSoft } as React.CSSProperties}><section className="detail-hero"><div className="detail-top"><Link to="/" className="back-link"><ArrowLeft size={16} /> Back to all projects</Link><span>{project.index} / 15</span></div><div className="detail-title"><span className="eyebrow">{project.eyebrow}</span><h1>{project.title}<span className="dot">.</span></h1><p>{project.description}</p></div><div className="detail-visual"><img src={project.image} alt={`${project.title} project`} /><div className="visual-caption"><span>{project.category}</span><span>Scroll to discover ↓</span></div></div></section><section className="detail-intro"><div className="section-label">The experience</div><div><p className="detail-lead">{project.longDescription}</p><div className="tag-list">{project.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></div><div className="detail-stat"><strong>{project.stat}</strong><span>{project.statLabel}</span></div></section><section className="detail-grid"><div className="detail-block dark-block"><span className="block-number">01</span><h2>Designed to<br /><em>stay with you.</em></h2><p>A considered system of typography, motion and atmosphere. Every decision creates a little more room for the idea to land.</p></div><div className="detail-block image-block"><img src={projects[(currentIndex + 3) % projects.length].image} alt="Atmospheric visual" /></div><div className="detail-block quote-block"><span className="quote-mark">“</span><p>The details are not the details. They make the design.</p><span className="quote-by">— Charles Eames</span></div></section><section className="next-project"><span className="section-label">Keep exploring</span><Link to={next.route}><span>Next project</span><h2>{next.title} <ArrowUpRight /></h2></Link><div className="prev-next"><Link to={previous.route}><ArrowLeft /> {previous.title}</Link><Link to="/">All projects <ArrowRight /></Link></div></section></main>
}
function Footer() { return <footer className="footer"><div><Logo /><p>A living archive of distinct<br />digital worlds.</p></div><div className="footer-links"><div><span>Explore</span><a href="#projects">Projects</a><a href="#categories">Categories</a><a href="#about">About</a></div><div><span>Connect</span><a href="https://github.com/alejandromontillamurillo-cell/mi-proyecto-prueba" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={13} /></a><a href="mailto:hello@creativewebuniverse.studio">Email <ArrowUpRight size={13} /></a></div></div><div className="footer-bottom"><span>© 2024 Creative Web Universe</span><span>Made with intention / Somewhere on the web</span></div></footer> }
export default function App() { const [menuOpen, setMenuOpen] = useState(false); const location = useLocation(); const navigate = useNavigate(); useEffect(() => { setMenuOpen(false) }, [location.pathname]); return <><Header onMenu={() => setMenuOpen(true)} />{menuOpen && <MobileMenu close={() => setMenuOpen(false)} />}{location.pathname === '/' ? <Home /> : <Detail />}{location.pathname !== '/' && <button className="floating-home" onClick={() => navigate('/')}><ArrowLeft size={17} /> All projects</button>}</> }
